name: GitHub Pages

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [ trigger-workflow ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout Config
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          repository: s9latimm/.dotfiles
          ref: master
          path: .config
          submodules: false

      - name: Install Config
        shell: bash
        working-directory: .config/python
        run: |
          python3 -m pip install -r requirements.txt

      - name: Checkout Portfolio
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          repository: s9latimm/portfolio
          ref: master
          path: portfolio
          ssh-key: ${{ secrets.SSH_PORTFOLIO }}
          submodules: false

      - name: Build Portfolio
        shell: bash
        working-directory: .config/python
        run: |
          python3 src/minimize.py --replace ../../../portfolio/web/

      - name: Upload Portfolio
        uses: actions/upload-artifact@v4
        with:
          name: portfolio
          retention-days: 1
          if-no-files-found: error
          overwrite: true
          path: |
            portfolio/web/index.html
            portfolio/web/robots.txt
            portfolio/web/sitemap.xml
            portfolio/web/css/
            portfolio/web/js/
            portfolio/web/json/
            portfolio/web/files/
            portfolio/web/images/
            portfolio/web/fonts/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download Portfolio
        uses: actions/download-artifact@v4
        with:
          name: portfolio
          path: .

      - name: Upload Page
        uses: actions/upload-pages-artifact@v3
        with:
          retention-days: 1
          path: .

      - name: Deploy Page
        id: deployment
        uses: actions/deploy-pages@v4
